version: "3.8"
services:
  xray-daemon:
      image: "amazon/aws-xray-daemon"
      environment:
        AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
        AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
        AWS_REGION: "${AWS_REGION}"
      command:
        - "xray -o -b xray-daemon:2000"
      ports:
        - 2000:2000/udp

      networks:
      - cruddur-net
  backend-flask:
    env_file:
        - .env.backend-flask
      
    build: ./backend-flask
    ports:
      - "4567:4567"
    depends_on:
      - otel-collector
    volumes:
      - ./backend-flask:/backend-flask

    networks:
      - cruddur-net
  frontend-react-js:
    env_file:
        - .env.frontend-react-js
      

    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js

    networks:
      - cruddur-net
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

    networks:
      - cruddur-net
  dynamodb-local:
      user: root
      command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
      image: "amazon/dynamodb-local:latest"
      container_name: dynamodb-local
      ports:
        - "8000:8000"
      volumes:
        - "./docker/dynamodb:/home/dynamodblocal/data"
      working_dir: /home/dynamodblocal

      networks:
      - cruddur-net
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector
    environment:
      HONEYCOMB_API_KEY: "${HONEYCOMB_API_KEY}"
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./otel/otel-collector-config.yml:/etc/otel-collector-config.yaml

    ports:
      # - 13133:13133 # health_check extension
      - 4318:4318 # OTLP http receiver
      # - 4317:4317 #OTLP grpc
      # - 55679:55679 # zpages extension   
    networks:
      - cruddur-net
networks: 
  cruddur-net:
    driver: bridge
    name: cruddur-net
volumes:
  db:
    driver: local
  